#!/usr/bin/env python
from PIL.ExifTags import TAGS
from PIL import Image
from PIL.ExifTags import GPSTAGS

def get_exif(filename):
    image = Image.open(filename)
    image.verify()
    return image._getexif()

exif = get_exif('DSCN0010.jpg')
#print(exif)





def get_labeled_exif(exif):
    labeled = {}
    print("The following types of data was found in the image")
    for (key, val) in exif.items():
        labeled[TAGS.get(key)] = val
        print(TAGS.get(key)," - " ,val)
        
    return labeled
    
exif = get_exif('DSCN0010.jpg')
labeled = get_labeled_exif(exif)
#print(labeled)




def get_geotagging(exif):
    if not exif:
        print("No EXIF metadata found")

    else:

        geotagging = {}
        for (idx, tag) in TAGS.items():
            if tag == 'GPSInfo':
                if idx not in exif:
                    print("No EXIF geotagging found")
                else:

                    for (key, val) in GPSTAGS.items():
                        if key in exif[idx]:
                            geotagging[val] = exif[idx][key]

        return geotagging

exif = get_exif('DSCN0010.jpg')
geotags = get_geotagging(exif)
#print(geotags)
